# Generated by Django 4.0.4 on 2022-08-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_name', models.TextField(max_length=50)),
                ('business_platform', models.TextField(max_length=50)),
                ('product_service', models.TextField(max_length=50)),
                ('company_website', models.TextField(max_length=50)),
            ],
        ),
    ]
