# Generated by Django 4.1 on 2022-08-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("terms77", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="company_policies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("uses_personal_info", models.BooleanField()),
                ("uses_user_acct", models.BooleanField()),
                ("uses_third_party_services", models.BooleanField()),
                ("uses_newsletter", models.BooleanField()),
                ("uses_user_upload_images", models.BooleanField()),
                ("uses_underage", models.BooleanField()),
                ("uses_ads", models.BooleanField()),
                ("uses_customer_data", models.BooleanField()),
                ("uses_retargeting_advertising", models.BooleanField()),
                ("uses_money", models.BooleanField()),
                ("promoted_company", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="company_policy_contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("uses_email", models.BooleanField()),
                ("uses_website", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fullname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("password", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("company_address", models.TextField(max_length=50)),
                ("country", models.TextField(max_length=50)),
                (
                    "company_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="terms77.users"
                    ),
                ),
            ],
        ),
    ]
