# Generated by Django 4.0.6 on 2022-08-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms77', '0002_remove_companies_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_names', models.TextField(default='', max_length=50)),
                ('business_platforms', models.TextField(default='', max_length=50)),
                ('product_services', models.TextField(default='', max_length=50)),
                ('company_websites', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
