# Generated by Django 4.0.6 on 2022-08-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms77', '0004_companies_user_policies_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policies',
            name='user',
        ),
        migrations.AlterField(
            model_name='companies',
            name='business_platform',
            field=models.TextField(max_length=50, null=True, verbose_name='Business Platform'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.TextField(max_length=50, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_website',
            field=models.TextField(max_length=50, null=True, verbose_name='Company Website'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='product_service',
            field=models.TextField(max_length=50, null=True, verbose_name='Product Service'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='business_platforms',
            field=models.TextField(max_length=50, null=True, verbose_name='Business Platform'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='company_names',
            field=models.TextField(max_length=50, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='company_websites',
            field=models.TextField(max_length=50, null=True, verbose_name='Company Website'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='product_services',
            field=models.TextField(max_length=50, null=True, verbose_name='Product Service'),
        ),
    ]
